# Generated by Django 6.0.4 on 2026-04-18 19:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DiscoveryJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_range', models.CharField(max_length=50)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('discovered_count', models.IntegerField(default=0)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='ThresholdRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('policy_type', models.CharField(choices=[('global', 'Global Policy'), ('specific', 'Node Specific')], default='global', max_length=10)),
                ('node_filter', models.CharField(blank=True, help_text="Filter by node label — e.g. 'firewall'. Used for global policies.", max_length=100)),
                ('node_id', models.CharField(blank=True, help_text='Specific node ID. Used for node specific policies.', max_length=100)),
                ('resource_id', models.CharField(blank=True, max_length=255)),
                ('metric', models.CharField(max_length=100)),
                ('operator', models.CharField(choices=[('>', 'Greater than'), ('<', 'Less than'), ('>=', 'Greater than or equal'), ('<=', 'Less than or equal')], default='>', max_length=3)),
                ('threshold', models.FloatField()),
                ('action', models.CharField(choices=[('alert', 'Alert only'), ('quarantine', 'Quarantine node'), ('shutdown', 'SNMP shutdown')], max_length=20)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='NodeAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('node_id', models.CharField(max_length=50)),
                ('node_label', models.CharField(max_length=100)),
                ('action_taken', models.CharField(max_length=50)),
                ('triggered_at', models.DateTimeField(auto_now_add=True)),
                ('resolved', models.BooleanField(default=False)),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolved_actions', to=settings.AUTH_USER_MODEL)),
                ('rule', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='monitoring.thresholdrule')),
            ],
            options={
                'ordering': ['-triggered_at'],
            },
        ),
    ]
